# Generated by Django 4.0.6 on 2022-07-05 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='double',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 5, 12, 20, 27, 997368)),
        ),
    ]
